export default function Privacy() {
  return (
    <div style={{ background: '#0C0C0C', minHeight: '100vh', color: '#fff', fontFamily: "'DM Sans', sans-serif", padding: '80px 24px' }}>
      <div style={{ maxWidth: 800, margin: '0 auto' }}>
        <a href="/" style={{ color: '#C9A962', fontSize: 14, textDecoration: 'none', display: 'block', marginBottom: 40 }}>← Back to FlipLedger</a>
        <h1 style={{ fontSize: 36, fontWeight: 800, marginBottom: 8 }}>Privacy Policy</h1>
        <p style={{ color: 'rgba(255,255,255,0.4)', marginBottom: 48 }}>Last updated: March 23, 2026</p>

        {[
          { title: '1. Introduction', body: `FlipLedger ("we," "us," or "our") operates flipledgerhq.com and the FlipLedger platform. This Privacy Policy explains how we collect, use, disclose, and protect your information when you use our Service. By creating an account and using FlipLedger, you agree to the collection and use of information in accordance with this policy.` },
          { title: '2. Information We Collect', body: `Account Information: When you create an account, we collect your email address and create a secure user profile.\n\nTransaction Data: We collect sales data, purchase costs, fees, profits, expenses, mileage, and inventory information that you enter manually or sync from connected platforms (StockX, eBay, and others).\n\nPlatform OAuth Tokens: When you connect StockX or eBay, we store encrypted OAuth access tokens to retrieve your sales data on your behalf. We never store your platform passwords.\n\nFinancial Data: We store cost basis information, sale prices, profit margins, sourcing store and location data (if provided), and tax-related data that you enter.\n\nUsage Data: We may collect anonymized usage information such as features used and session duration to improve the platform.\n\nCookies and Local Storage: We use cookies and browser local storage to maintain your authenticated session and remember your preferences. By using FlipLedger, you consent to our use of cookies for these purposes.` },
          { title: '3. How We Use Your Information', body: `We use your information to:\n\n• Operate and provide the FlipLedger platform\n• Generate profit reports, Schedule C tax exports, and analytics\n• Sync your sales data from connected platforms\n• Power platform intelligence features using anonymized aggregate data\n• Communicate with you about your account and the Service\n• Process payments through Stripe\n• Improve the platform and develop new features\n• Comply with legal obligations` },
          { title: '4. How We Use Aggregated Data', body: `Like most platforms, FlipLedger uses anonymized, aggregated data across all users to make the product smarter for everyone. This powers features like Cop Check market insights, buying recommendations, and industry trend reports.\n\nWe may also share anonymized market intelligence with brands, retailers, wholesalers, and research partners — for example, reporting that "the average resale margin for a specific product is 35% across thousands of transactions."\n\nYour personal data is never part of this. We never share your individual sales, costs, sourcing locations, or any information that identifies you. Only anonymous statistical patterns are ever used or shared.\n\nBy using FlipLedger you agree to this use of anonymized aggregated data.` },
          { title: '5. Data Storage and Security', body: `Your data is stored securely using Supabase with row-level security (RLS) enabled. This means your data is cryptographically isolated — only your authenticated account can access your records.\n\nWe use industry-standard encryption for data in transit (HTTPS/TLS) and at rest. While we take reasonable precautions, no system is 100% secure and we cannot guarantee absolute security.\n\nIn the event of a data breach that affects your personal information, we will notify you as required by applicable law.` },
          { title: '6. Third-Party Services', body: `We use the following third-party services to operate the platform:\n\n• Supabase — secure database and authentication\n• Stripe — payment processing (we never store full card details)\n• StockX API — to sync your StockX sales data\n• eBay API — to sync your eBay sales data\n• Vercel — hosting and infrastructure\n• Anthropic Claude API — AI-powered features including receipt scanning\n\nEach third party has their own privacy policy governing their use of your data.` },
          { title: '7. California Residents — CCPA Rights', body: `If you are a California resident, you have additional rights under the California Consumer Privacy Act (CCPA):\n\n• Right to Know: You may request information about the personal data we collect, use, and share.\n• Right to Delete: You may request deletion of your personal data.\n• Right to Opt-Out: FlipLedger does not sell your personal information. We do share anonymized, aggregated data as described in Section 4, but this does not constitute a "sale" under CCPA as it cannot be used to identify you.\n• Right to Non-Discrimination: We will not discriminate against you for exercising your CCPA rights.\n\nTo exercise these rights, contact support@flipledgerhq.com.` },
          { title: '8. Do Not Sell My Personal Information', body: `FlipLedger does not sell your personal information to third parties. We may share anonymized, aggregated data that cannot identify you, as described in Section 4. If you have questions, contact support@flipledgerhq.com.` },
          { title: '9. Data Retention', body: `We retain your account data for as long as your account is active. If you cancel your subscription, your data remains stored for 90 days before deletion, giving you time to export your records.\n\nYou may request immediate deletion of your account and all associated data at any time by contacting support@flipledgerhq.com.` },
          { title: '10. Your Rights', body: `You have the right to:\n\n• Access your personal data at any time through the platform\n• Export your data in CSV format\n• Correct inaccurate data\n• Request deletion of your account and all data\n• Disconnect platform integrations at any time\n\nTo exercise these rights, contact support@flipledgerhq.com.` },
          { title: "11. Children's Privacy", body: `FlipLedger is not directed to children under 18 years of age. We do not knowingly collect personal information from anyone under 18. If you are under 18, do not use the Service.` },
          { title: '12. Changes to This Policy', body: `We may update this Privacy Policy from time to time. We will notify you of significant changes by email or by posting a notice on the platform at least 14 days before the changes take effect. Your continued use of the Service after changes constitutes acceptance of the updated policy.` },
          { title: '13. Contact Us', body: `FlipLedger\nsupport@flipledgerhq.com\nSalt Lake City, Utah, United States` },
        ].map((section, i) => (
          <div key={i} style={{ marginBottom: 40 }}>
            <h2 style={{ fontSize: 20, fontWeight: 700, color: '#C9A962', marginBottom: 12 }}>{section.title}</h2>
            <p style={{ fontSize: 15, lineHeight: 1.8, color: 'rgba(255,255,255,0.7)', whiteSpace: 'pre-line' }}>{section.body}</p>
          </div>
        ))}
        <div style={{ borderTop: '1px solid rgba(255,255,255,0.06)', paddingTop: 32, marginTop: 48, textAlign: 'center' }}>
          <p style={{ color: 'rgba(255,255,255,0.3)', fontSize: 13 }}>© 2026 FlipLedger. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}
