export default function Terms() {
  return (
    <div style={{ background: '#0C0C0C', minHeight: '100vh', color: '#fff', fontFamily: "'DM Sans', sans-serif", padding: '80px 24px' }}>
      <div style={{ maxWidth: 800, margin: '0 auto' }}>
        <a href="/" style={{ color: '#C9A962', fontSize: 14, textDecoration: 'none', display: 'block', marginBottom: 40 }}>← Back to FlipLedger</a>
        <h1 style={{ fontSize: 36, fontWeight: 800, marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ color: 'rgba(255,255,255,0.4)', marginBottom: 48 }}>Last updated: April 28, 2026</p>

        {[
          { title: '1. Agreement to Terms', body: `By creating an account, accessing, or using FlipLedger ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, you may not use the Service. These Terms constitute a legally binding agreement between you and FlipLedger.` },
          { title: '2. Description of Service', body: `FlipLedger is a reseller business management platform that helps users track inventory, sales, expenses, and profits across resale platforms including StockX and eBay. The Service includes profit analytics, Schedule C tax preparation assistance, market intelligence features, and platform integrations.\n\nFlipLedger is a software tool only. We are not a resale platform, marketplace, financial institution, or licensed tax advisor.` },
          { title: '3. Eligibility', body: `You must be at least 18 years old to use FlipLedger. By using the Service, you represent that you are at least 18 years old and have the legal capacity to enter into this agreement. If you are using the Service on behalf of a business, you represent that you have authority to bind that business to these Terms.` },
          { title: '4. Account Registration', body: `You must provide accurate, current, and complete information when creating your account. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.\n\nYou agree to notify us immediately at support@flipledgerhq.com if you suspect unauthorized access to your account. We are not liable for any loss resulting from unauthorized use of your account.` },
          { title: '5. Subscription and Payment', body: `FlipLedger is offered as a paid subscription service.\n\n• Current pricing is $149/month\n• Payments are processed securely through Stripe\n• Subscriptions automatically renew each billing period unless cancelled\n• You may cancel your subscription at any time through your account settings\n• We do not provide refunds for partial billing periods\n• Failed payments may result in suspension of your account\n• We reserve the right to change pricing with 30 days advance notice to active subscribers\n• Disputes about charges must be submitted within 60 days of the charge` },
          { title: '6. TAX AND FINANCIAL DISCLAIMER', body: `FLIPLEDGER IS NOT A LICENSED CPA, TAX ADVISOR, TAX PREPARER, FINANCIAL ADVISOR, OR ATTORNEY.\n\n• Schedule C reports, tax summaries, and all financial exports are for INFORMATIONAL AND ORGANIZATIONAL PURPOSES ONLY\n• FlipLedger does NOT provide tax advice, legal advice, or financial advice\n• The accuracy of all reports depends entirely on the accuracy of data you enter\n• FlipLedger makes NO guarantee that its reports comply with current IRS regulations or your specific tax obligations\n• You are solely responsible for the accuracy of your tax filings\n• You should ALWAYS consult a licensed CPA or tax professional before filing tax returns\n• FlipLedger shall not be liable for any tax penalties, audits, fines, or legal consequences arising from your use of our reports\n\nIF YOU ARE UNSURE ABOUT YOUR TAX OBLIGATIONS, CONSULT A QUALIFIED TAX PROFESSIONAL.` },
          { title: '7. Platform Integrations', body: `By connecting StockX, eBay, or other third-party platforms, you:\n\n• Authorize FlipLedger to access your sales data on your behalf using official APIs\n• Represent that you have the right to grant such access\n• Acknowledge that FlipLedger is NOT affiliated with, endorsed by, or an official partner of StockX, eBay, or any other platform\n\nWe are not responsible for changes to third-party APIs, data inaccuracies from connected platforms, or interruptions in platform connectivity. Third-party platforms may revoke API access at any time without notice.` },
          { title: '8. Acceptable Use', body: `You agree not to:\n\n• Use the Service for any illegal purpose or in violation of any applicable laws\n• Use the Service to track, facilitate, or profit from the sale of counterfeit, stolen, or prohibited goods\n• Violate the terms of service of any connected platform\n• Attempt to reverse engineer, copy, or create derivative works of the Service\n• Share, sell, or transfer your account credentials to others\n• Use automated tools to scrape or extract data from the Service\n• Attempt to gain unauthorized access to any part of the Service\n• Use the Service in any way that could damage, disable, or impair the platform\n\nViolation may result in immediate account termination without refund.` },
          { title: '9. Counterfeit and Illegal Goods', body: `FlipLedger is strictly a bookkeeping and analytics tool. You are solely responsible for ensuring that all items you track, list, or sell are authentic, legally obtained, and compliant with all applicable laws and platform policies.\n\nFlipLedger has no involvement in your actual transactions and takes no responsibility for the authenticity or legality of items you resell. We reserve the right to terminate accounts we believe are being used to facilitate illegal activity.` },
          { title: '10. Intellectual Property', body: `FlipLedger and all its content, features, and functionality are owned by FlipLedger and are protected by copyright, trademark, and other intellectual property laws.\n\nYou retain ownership of all data you enter into the platform. By using the Service, you grant FlipLedger a limited license to store, process, and use your data to provide the Service and as described in our Privacy Policy.\n\nYou may not copy, modify, distribute, or create derivative works based on our platform without our express written permission.` },
          { title: '11. Force Majeure', body: `FlipLedger shall not be liable for any failure or delay in performance resulting from causes beyond our reasonable control, including but not limited to: acts of God, internet outages, third-party API changes or shutdowns (including StockX and eBay), government actions, cyberattacks, or other circumstances outside our control.` },
          { title: '12. Your Data and Aggregated Data', body: `You retain ownership of all data you enter into FlipLedger. By using the Service, you grant FlipLedger a limited license to store and process your data to provide the Service, and to use anonymized, aggregated versions of your transaction data to improve platform features and market intelligence. No individual data is ever identified or shared. See our Privacy Policy for full details.` },
          { title: '13. Disclaimers of Warranty', body: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND.\n\nWE DISCLAIM ALL WARRANTIES INCLUDING:\n• Warranties of merchantability or fitness for a particular purpose\n• Warranties that the Service will be uninterrupted or error-free\n• Warranties regarding the accuracy of synced sales data from third-party platforms\n• Warranties that reports comply with tax regulations\n• Warranties regarding market intelligence accuracy` },
          { title: '14. Limitation of Liability', body: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, FLIPLEDGER SHALL NOT BE LIABLE FOR:\n\n• Any indirect, incidental, special, consequential, or punitive damages\n• Loss of profits, revenue, data, or business opportunities\n• Tax penalties, audits, or legal consequences from use of our reports\n• Losses from inaccurate synced data from third-party platforms\n• Losses from unauthorized account access\n• Service interruptions caused by third-party platform changes\n\nIN NO EVENT SHALL FLIPLEDGER'S TOTAL LIABILITY EXCEED THE AMOUNT YOU PAID IN THE 3 MONTHS PRECEDING THE CLAIM.` },
          { title: '15. Indemnification', body: `You agree to indemnify and hold harmless FlipLedger and its officers, directors, employees, and agents from any claims, damages, losses, or expenses (including reasonable attorneys' fees) arising from your use of the Service, your violation of these Terms, your violation of any third-party rights, or any inaccuracy in data you provide.` },
          { title: '16. Termination', body: `Either party may terminate this agreement at any time.\n\nYou may cancel at any time through your account settings. Cancellation takes effect at the end of your current billing period.\n\nWe reserve the right to suspend or terminate accounts immediately if you violate these Terms, engage in fraudulent or illegal activity, or for any other reason at our sole discretion. Upon termination, your right to use the Service ceases immediately.` },
          { title: '17. Governing Law and Dispute Resolution', body: `These Terms are governed by the laws of the State of Utah, United States.\n\nAny disputes shall be resolved through binding arbitration in Salt Lake City, Utah, under the rules of the American Arbitration Association, except that either party may seek injunctive relief in court for intellectual property violations.\n\nYou waive any right to participate in a class action lawsuit against FlipLedger.\n\nAny claims must be brought within one (1) year of the event giving rise to the claim.` },
          { title: '18. Changes to Terms', body: `We may update these Terms at any time. We will notify you of material changes by email or platform notice at least 30 days before changes take effect. Your continued use after changes constitutes acceptance.` },
          { title: '19. Auto-Delist and Automated Features', body: `By using FlipLedger's auto-delist or any automated cross-platform features, you acknowledge and agree that:\n\n• Automated delisting depends on third-party APIs (StockX, eBay, etc.) that may fail, delay, or behave unexpectedly without notice\n• You are solely responsible for monitoring your active listings across all platforms\n• You should regularly verify that delists have completed successfully on each platform\n• FlipLedger is NOT responsible for double-sales, double-listings, platform penalties, lost sales, refunded buyers, customer service issues, account suspensions, or any other consequences resulting from delist failures, delays, or errors\n• If a sale occurs and the corresponding delist does not fire correctly, you are responsible for manually delisting on the affected platform and handling any consequences\n• Auto-delist is provided as a convenience tool, not a guarantee\n• FlipLedger's liability for any delist-related issue is limited as described in Section 14 (Limitation of Liability)\n\nYou should treat FlipLedger as an aid to your business operations, not a replacement for your own oversight and verification of your listings.` },
          { title: '20. Contact', body: `FlipLedger\nsupport@flipledgerhq.com\nSalt Lake City, Utah, United States` },
        ].map((section, i) => (
          <div key={i} style={{ marginBottom: 40 }}>
            <h2 style={{ fontSize: 20, fontWeight: 700, color: '#C9A962', marginBottom: 12 }}>{section.title}</h2>
            <p style={{ fontSize: 15, lineHeight: 1.8, color: 'rgba(255,255,255,0.7)', whiteSpace: 'pre-line' }}>{section.body}</p>
          </div>
        ))}
        <div style={{ borderTop: '1px solid rgba(255,255,255,0.06)', paddingTop: 32, marginTop: 48, textAlign: 'center' }}>
          <p style={{ color: 'rgba(255,255,255,0.3)', fontSize: 13 }}>© 2026 FlipLedger. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}
